version: '3.8'

services:
  # Frontend - React + Vite
  frontend:
    build:
      context: ./react-skill-up-india-vite
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
      - VITE_AI_URL=http://localhost:8000
    depends_on:
      - backend
      - ai
    networks:
      - app-network

  # Backend - Spring Boot
  backend:
    build:
      context: ./skill-up-india
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    networks:
      - app-network

  # AI Service - FastAPI
  ai:
    build:
      context: ./ai-skill-up-india
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    env_file:
      - ./ai-skill-up-india/.env
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge